"""中文翻译引擎 —— 把 exercises-dataset 的英文动作名与分类标签翻成中文。

设计：双层翻译
  1. EXACT_OVERRIDE：常见/习惯用语的精确整句覆盖（保证高频动作质量）
  2. 规则引擎：装备前缀 + 动作主体 + 修饰词，按健身命名规律组合翻译长尾

未命中规则的生僻词会回退显示英文，保证不丢字段。
"""

import re
from typing import Optional

# ----------------------------------------------------------------------------
# 1. 装备（出现在动作名里，作为前缀）—— 按长度降序贪心匹配
# ----------------------------------------------------------------------------
EQUIPMENT = {
    "smith machine": "史密斯机",
    "body weight": "自重",
    "bodyweight": "自重",
    "e-z bar": "EZ杆",
    "e z bar": "EZ杆",
    "ez bar": "EZ杆",
    "olympic barbell": "奥林匹克杠铃",
    "trap bar": "六角杠铃",
    "medicine ball": "药球",
    "swiss ball": "瑞士球",
    "stability ball": "健身球",
    "exercise ball": "健身球",
    "bosu ball": "波速球",
    "foam roll": "泡沫轴",
    "foam roller": "泡沫轴",
    "leverage machine": "杠杆器械",
    "stationary bike": "固定单车",
    "elliptical machine": "椭圆机",
    "elliptical": "椭圆机",
    "step machine": "台阶机",
    "stepmill": "台阶机",
    "sled machine": "雪橇机",
    "sled": "雪橇",
    "upper body ergometer": "上肢测功仪",
    "skierg": "滑雪机",
    "booty sprout": "臀推机",
    "resistance band": "弹力带",
    "assisted": "辅助",
    "cable": "绳索",
    "dumbbell": "哑铃",
    "barbell": "杠铃",
    "kettlebell": "壶铃",
    "band": "弹力带",
    "machine": "器械",
    "ball": "球",
    "rope": "绳",
    "tire": "轮胎",
    "roller": "滚筒",
    "wheel": "轮",
    "box": "箱",
    "plate": "片",
    "chain": "铁链",
    "mat": "垫",
    "wall": "墙",
    "bar": "杆",
    "hammer": "锤",
    "smith": "史密斯",
    "lever": "杠杆",
    "weighted": "负重",
}

# ----------------------------------------------------------------------------
# 2. 动作主体（最长优先）
# ----------------------------------------------------------------------------
MOVEMENT = {
    "bench press": "卧推",
    "push press": "借力推举",
    "push jerk": "挺举",
    "overhead press": "过头推举",
    "shoulder press": "肩推",
    "military press": "军推",
    "chest press": "胸推",
    "incline press": "上斜推举",
    "decline press": "下斜推举",
    "arnold press": "阿诺德推举",
    "landmine press": "地雷管推举",
    "floor press": "地面推举",
    "pullover": "颈后臂屈伸",
    "pull-over": "颈后臂屈伸",
    "pull up": "引体向上",
    "pull-up": "引体向上",
    "chin up": "反握引体",
    "chin-up": "反握引体",
    "muscle up": "双力臂",
    "dip": "臂屈伸",
    "push up": "俯卧撑",
    "push-up": "俯卧撑",
    "clap push up": "击掌俯卧撑",
    "diamond push up": "钻石俯卧撑",
    "pike push up": "派克俯卧撑",
    "handstand push up": "倒立俯卧撑",
    "squat": "深蹲",
    "front squat": "前蹲",
    "overhead squat": "过头深蹲",
    "split squat": "分腿蹲",
    "bulgarian split squat": "保加利亚分腿蹲",
    "zercher squat": "泽奇深蹲",
    "goblet squat": "高脚杯深蹲",
    "sumo squat": "相扑深蹲",
    "hack squat": "哈克深蹲",
    "wall sit": "靠墙静蹲",
    "deadlift": "硬拉",
    "romanian deadlift": "罗马尼亚硬拉",
    "stiff leg deadlift": "直腿硬拉",
    "sumo deadlift": "相扑硬拉",
    "conventional deadlift": "传统硬拉",
    "rack pull": "架上硬拉",
    "snatch": "抓举",
    "clean": "翻站",
    "clean and jerk": "挺举",
    "hang clean": "悬垂翻",
    "thruster": "推举深蹲",
    "row": "划船",
    "bent over row": "俯身划船",
    "t bar row": "T杠划船",
    "t-bar row": "T杠划船",
    "upright row": "直立划船",
    "seated row": "坐姿划船",
    "inverted row": "反向划船",
    "gorilla row": "猩猩划船",
    "pendlay row": "彭德利划船",
    "fly": "飞鸟",
    "flye": "飞鸟",
    "chest fly": "夹胸",
    "cable crossover": "绳索交叉夹胸",
    "cable cross over": "绳索交叉夹胸",
    "lateral raise": "侧平举",
    "front raise": "前平举",
    "rear delt fly": "后束反向飞鸟",
    "rear delt raise": "后束上举",
    "reverse fly": "反向飞鸟",
    "face pull": "面拉",
    "shrug": "耸肩",
    "curl": "弯举",
    "hammer curl": "锤式弯举",
    "concentration curl": "集中弯举",
    "preacher curl": "牧师凳弯举",
    "incline curl": "上斜弯举",
    "spider curl": "蜘蛛弯举",
    "zottman curl": "佐特曼弯举",
    "wrist curl": "腕弯举",
    "extension": "伸展",
    "pushdown": "下压",
    "pulldown": "下拉",
    "pull down": "下拉",
    "skull crusher": "仰卧臂屈伸",
    "crunch": "卷腹",
    "sit up": "仰卧起坐",
    "sit-up": "仰卧起坐",
    "reverse crunch": "反向卷腹",
    "bicycle crunch": "自行车卷腹",
    "twisting sit up": "转体仰卧起坐",
    "twisting sit-up": "转体仰卧起坐",
    "jackknife sit up": "折刀仰卧起坐",
    "hanging leg raise": "悬垂举腿",
    "leg raise": "举腿",
    "knee raise": "举膝",
    "leg press": "腿举",
    "leg extension": "腿伸展",
    "leg curl": "腿弯举",
    "lying leg curl": "俯卧腿弯举",
    "seated leg curl": "坐姿腿弯举",
    "hip thrust": "臀推",
    "glute bridge": "臀桥",
    "glute kickback": "臀后踢",
    "kickback": "后踢",
    "lunge": "箭步蹲",
    "reverse lunge": "反向箭步蹲",
    "walking lunge": "行走箭步蹲",
    "side lunge": "侧箭步蹲",
    "curtsy lunge": "屈膝礼箭步蹲",
    "calf raise": "提踵",
    "standing calf raise": "站姿提踵",
    "seated calf raise": "坐姿提踵",
    "donkey calf raise": "驴式提踵",
    "bridge": "桥",
    "plank": "平板支撑",
    "side plank": "侧平板",
    "plank jack": "平板开合",
    "mountain climber": "登山者",
    "burpee": "波比跳",
    "jump rope": "跳绳",
    "jump": "跳",
    "box jump": "跳箱",
    "broad jump": "立定跳远",
    "clap jump": "击掌跳",
    "tuck jump": "收腹跳",
    "split jump": "分腿跳",
    "rope climb": "爬绳",
    "climb": "攀爬",
    "swing": "摆荡",
    "kettlebell swing": "壶铃摆荡",
    "twist": "转体",
    "russian twist": "俄罗斯转体",
    "wood chop": "伐木",
    "side bend": "体侧屈",
    "torso rotation": "躯干旋转",
    "windmill": "风车",
    "good morning": "早安式体前屈",
    "superman": "超人式",
    "bird dog": "鸟狗式",
    "dead bug": "死虫",
    "bear crawl": "熊爬",
    "crab walk": "蟹步",
    "fire hydrant": "消防栓式",
    "clamshell": "蚌式",
    "v up": "V字起身",
    "toe touch": "触脚尖",
    "heel touch": "触踵",
    "scissor kick": "剪刀踢",
    "flutter kick": "交替踢腿",
    "heel tap": "触踵",
    "march": "踏步",
    "high knees": "高抬腿",
    "butt kick": "踢臀",
    "kick": "踢",
    "punch": "出拳",
    "slam": "砸",
    "throw": "抛",
    "carry": "行走",
    "farmer carry": "农夫行走",
    "farmers walk": "农夫行走",
    "waiter walk": "侍者行走",
    "y raise": "Y字上举",
    "t raise": "T字上举",
    "w raise": "W字上举",
    "raise": "上举",
    "press": "推举",
    "push": "推",
    "pull": "拉",
    "drag": "拖拽",
    "hold": "保持",
    "stretch": "拉伸",
    "roll": "滚动",
    "squeeze": "挤压",
    "contract": "收缩",
    "flex": "弯举",
    "lift": "上提",
    "lower": "下放",
    "rotate": "旋转",
    "rotations": "旋转",
    "circles": "绕环",
    "circle": "绕环",
    "step up": "登阶",
    "step-up": "登阶",
    "step down": "下阶",
    "jumping jack": "开合跳",
    "jump jack": "开合跳",
    "crossover": "交叉",
    "cross over": "交叉",
    "cross body": "交叉",
    "cross-body": "交叉",
    "reach": "伸展",
    "touch": "触",
    "tap": "触",
    "abduction": "外展",
    "adduction": "内收",
    "pulse": "脉冲",
    "isometric": "等长",
    "iso": "等长",
    "hyperextension": "超伸",
    "hyper extension": "超伸",
    "reverse hyper": "反向超伸",
    "back extension": "背伸展",
    "neck stretch": "颈部拉伸",
    "neck rotations": "颈部旋转",
    "calf stretch": "小腿拉伸",
    "hamstring stretch": "腘绳肌拉伸",
    "quad stretch": "股四头拉伸",
    "chest stretch": "胸拉伸",
    "glute stretch": "臀拉伸",
    "shoulder stretch": "肩拉伸",
    "hip flexor stretch": "髋屈肌拉伸",
    "tricep stretch": "三头拉伸",
    "bicep stretch": "二头拉伸",
    "wrist stretch": "腕拉伸",
    "forearm stretch": "前臂拉伸",
    "ankle circles": "踝绕环",
    "wrist circles": "腕绕环",
    "rollout": "滚动",
    "rollerout": "滚动",
    "skullcrusher": "仰卧臂屈伸",
    "twisting": "转体",
    "cross body twist": "交叉转体",
    "behind head": "颈后",
    "behind neck": "颈后",
    "low bar": "低杠",
    "high bar": "高杠",
    "narrow stance": "窄距",
    "wide stance": "宽距",
    "reverse grip": "反握",
    "clean grip": "翻握",
    "vertical": "垂直",
    "rocking": "摇摆",
    "sitted": "坐姿",
    "siting": "坐姿",
    "pin": "销",
    "drag": "拖",
    "speed": "快速",
    "skier": "滑雪者",
    "jefferson": "杰弗逊",
    "guillotine": "吉约廷",
    "bradford": "布拉德福德",
    "palms down": "掌心向下",
    "palms up": "掌心向上",
    "v.2": "V2",
    "v. 2": "V2",
    "back of the head": "颈后",
    "over head": "过头",
    "stiff leg": "直腿",
    "pallof": "帕洛夫",
    "to skull": "",
    "squatting": "深蹲",
    "battling ropes": "战绳",
    "battling": "战",
    "yoga": "瑜伽",
    "pose": "式",
    "butterfly": "蝴蝶",
    "concentration": "集中",
    "pulley": "滑轮",
    "high pulley": "高位滑轮",
    "judo": "柔道",
    "flip": "翻",
    "range of motion": "全程",
    "v-bar": "V杆",
    "cable bar": "绳索",
    "cable rope": "绳索",
    "hip circles": "髋绕环",
    "knee circles": "膝绕环",
    "side lying": "侧卧",
    "leg lift": "举腿",
    "arm lift": "举臂",
    "head lift": "举头",
    "neck lift": "举颈",
    "running": "跑",
    "jog": "慢跑",
    "sprint": "冲刺",
    "walk": "走",
    "skip": "跳",
    "hop": "单脚跳",
    "slide": "滑步",
    "shuffle": "滑步",
    "lateral slide": "侧滑",
    "carioca": "交叉步",
    "inchworm": "尺蠖",
    "duck walk": "鸭步",
    "frog jump": "蛙跳",
    "donkey kick": "驴踢",
    "leg swing": "摆腿",
    "arm swing": "摆臂",
    "hip swing": "摆髋",
    "torso twist": "躯干扭转",
    "standing twist": "站姿转体",
    "seated twist": "坐姿转体",
    "tire flip": "翻轮胎",
    "tire hit": "砸轮胎",
    "sledge hammer": "锤击",
    "battle rope": "战绳",
    "rope wave": "绳波",
    "rope slam": "砸绳",
    "medicine ball slam": "药球砸",
    "medicine ball throw": "药球抛",
    "wall ball": "砸墙球",
    "box step": "箱登阶",
    "box squat": "箱深蹲",
    "pec deck": "夹胸机",
    "chest fly machine": "器械夹胸",
    "bench dip": "凳上臂屈伸",
    "lat pulldown": "高位下拉",
    "cable pulldown": "绳索下拉",
    "band pulldown": "弹力带下拉",
    "underhand pulldown": "反握下拉",
    "close grip pulldown": "窄握下拉",
    "wide grip pulldown": "宽握下拉",
    "straight arm pulldown": "直臂下拉",
    "single arm pulldown": "单臂下拉",
    "wall climb": "爬墙",
}

# ----------------------------------------------------------------------------
# 3. 修饰词
#    PREFIX：放在动作主体之前；SUFFIX：放在动作主体之后
# ----------------------------------------------------------------------------
MODIFIER_PREFIX = {
    "incline": "上斜",
    "decline": "下斜",
    "seated": "坐姿",
    "standing": "站姿",
    "lying": "仰卧",
    "prone": "俯卧",
    "supine": "仰卧",
    "kneeling": "跪姿",
    "single": "单",
    "single-arm": "单臂",
    "single-leg": "单腿",
    "one-arm": "单臂",
    "one-leg": "单腿",
    "alternating": "交替",
    "alternate": "交替",
    "bent": "俯身",
    "flat": "平板",
    "wide": "宽",
    "wide-grip": "宽握",
    "close": "窄",
    "close-grip": "窄握",
    "neutral": "对握",
    "neutral-grip": "对握",
    "reverse": "反向",
    "half": "半",
    "full": "全程",
    "double": "双",
    "weighted": "负重",
    "resisted": "抗阻",
    "suspended": "悬吊",
    "isometric": "等长",
    "eccentric": "离心",
    "concentric": "向心",
    "pause": "停顿",
    "slow": "慢速",
    "tempo": "节奏",
    "partial": "半程",
    "assisted": "辅助",
    "machine": "器械",
    "cable": "绳索",
    "dumbbell": "哑铃",
    "barbell": "杠铃",
    "kettlebell": "壶铃",
    "band": "弹力带",
    "bodyweight": "自重",
    "kipping": "借力",
    "scapular": "肩胛",
    "overhead": "过头",
    "floor": "地面",
    "straight": "直",
    "parallel": "平行",
    "forward": "前",
    "backward": "向后",
    "hanging": "悬垂",
    "internal": "内",
    "external": "外",
    "lateral": "侧",
    "plyo": "增强式",
    "hammer": "锤式",
    "smith": "史密斯",
    "lever": "杠杆",
    "grip": "握",
    "bench": "凳",
    "archer": "射手",
    "towel": "毛巾",
    "run": "跑",
    "support": "支撑",
    "pelvic": "骨盆",
    "tilt": "倾斜",
    "through": "过",
    "hyper": "超",
    "self": "自我",
    "inverse": "反向",
    "side": "侧",
    "front": "前",
    "rear": "后",
    "middle": "中",
}

MODIFIER_SUFFIX = {
    "alternating": "交替",
    "alternate": "交替",
    "single": "单",
    "single-arm": "单臂",
    "single-leg": "单腿",
    "eccentric": "离心",
    "partial": "半程",
    "pause": "停顿",
    "slow": "慢速",
    "weighted": "负重",
    "resisted": "抗阻",
    "suspended": "悬吊",
    "twist": "转体",
    "twisting": "转体",
    "diagonal": "对角",
    "isometric": "等长",
    "to failure": "至力竭",
    "drop": "递减",
    "superset": "超级组",
    "grip": "握",
}

# ----------------------------------------------------------------------------
# 4. 肌肉 / 部位词汇（作为动作名里的修饰，放在主体之前）
# ----------------------------------------------------------------------------
MUSCLE_WORD = {
    "chest": "胸",
    "pec": "胸",
    "pecs": "胸",
    "bicep": "二头",
    "biceps": "二头",
    "tricep": "三头",
    "triceps": "三头",
    "forearm": "前臂",
    "forearms": "前臂",
    "arm": "臂",
    "arms": "臂",
    "calf": "小腿",
    "calves": "小腿",
    "glute": "臀",
    "glutes": "臀",
    "hamstring": "腘绳",
    "hamstrings": "腘绳",
    "quad": "股四头",
    "quads": "股四头",
    "quadricep": "股四头",
    "quadriceps": "股四头",
    "ab": "腹",
    "abs": "腹",
    "oblique": "腹斜",
    "obliques": "腹斜",
    "delt": "三角肌",
    "delts": "三角肌",
    "deltoid": "三角肌",
    "deltoids": "三角肌",
    "trap": "斜方",
    "traps": "斜方",
    "lat": "背阔",
    "lats": "背阔",
    "shoulder": "肩",
    "shoulders": "肩",
    "neck": "颈",
    "hip": "髋",
    "hipflexor": "髋屈",
    "hip flexor": "髋屈",
    "core": "核心",
    "spine": "脊柱",
    "back": "背",
    "leg": "腿",
    "legs": "腿",
    "hand": "手",
    "foot": "足",
    "feet": "足",
    "knee": "膝",
    "knees": "膝",
    "ankle": "踝",
    "wrist": "腕",
    "elbow": "肘",
    "toe": "趾",
    "toes": "趾",
    "heel": "踵",
    "finger": "指",
    "thumb": "拇指",
    "lower": "下",
    "upper": "上",
    "inner": "内",
    "outer": "外",
}

# 其他单词（翻译或跳过）
WORD_MAP = {
    "exercise": "",
    "training": "",
    "workout": "",
    "stability": "",
    "on": "",
    "the": "",
    "a": "",
    "an": "",
    "with": "带",
    "using": "用",
    "to": "",
    "and": "",
    "or": "",
    "of": "",
    "into": "",
    "from": "",
    "over": "",
    "under": "",
    "get": "",
    "up": "",
    "out": "",
    "ing": "",
    "stiff": "直",
    "revers": "反向",
    "jm": "JM",
    "high": "高",
    "low": "低",
    "short": "短",
    "long": "长",
    "left": "左",
    "right": "右",
    "spin": "旋转",
    "rotation": "旋转",
    "rotations": "旋转",
    "range": "幅度",
    "motion": "活动",
    "down": "下",
    "deep": "深",
    "hands": "手",
    "against": "靠",
    "palm": "掌",
    "palms": "掌",
    "elevated": "抬高",
    "tuck": "收",
    "drive": "驱动",
    "chair": "椅",
    "basic": "基础",
    "rotational": "旋转",
    "curtsey": "屈膝礼",
    "cocoons": "茧式",
    "cambered": "弧杆",
    "cycle": "单车",
    "cross": "交叉",
    "trainer": "机",
    "cage": "架",
    "stirrups": "吊环",
    "sz": "SZ",
    "sz-bar": "SZ杆",
    "pro": "专业",
    "kayak": "皮划艇",
    "captains": "",
    "rocky": "",
    "thibaudeau": "",
    "stabilization": "稳定",
    "activation": "激活",
    "mobilization": "活动",
    "warm": "热身",
    "warmup": "热身",
    "cool": "放松",
    "cooldown": "放松",
    "dynamic": "动态",
    "static": "静态",
    "active": "主动",
    "passive": "被动",
    "release": "放松",
    "recovery": "恢复",
    "prehab": "预康",
    "rehab": "康复",
    "corrective": "矫正",
    "balance": "平衡",
    "coordination": "协调",
    "endurance": "耐力",
    "power": "爆发",
    "strength": "力量",
    "stability": "稳定",
    "mobility": "灵活",
    "cardio": "有氧",
    "aerobic": "有氧",
    "hiit": "高强度间歇",
    "circuit": "循环",
    "tabata": "塔巴塔",
    "beginner": "初级",
    "advanced": "进阶",
    "intermediate": "中级",
    "version": "版",
    "variation": "变式",
    "variant": "变式",
    "modified": "改良",
    "standard": "标准",
    "classic": "经典",
    "explosive": "爆发",
    "controlled": "控制",
    "male": "",
    "female": "",
    "s": "",
    "d": "",
    "ez": "EZ",
    "y": "Y",
    "v": "V",
    "pov": "",
    "attachment": "",
    "attachments": "",
    "blaster": "",
    "fixed": "固定",
    "blade": "刃",
    "barbell": "杠铃",
    "3/4": "四分之三",
    "1/2": "半",
    "90": "90",
    "45": "45",
    "degree": "度",
    "deg": "度",
    "degrees": "度",
    "one": "一",
    "two": "二",
    "three": "三",
    "four": "四",
    "five": "五",
    "six": "六",
    "8": "8",
    "10": "10",
    "12": "12",
    "15": "15",
    "20": "20",
}

# ----------------------------------------------------------------------------
# 5. 精确整句覆盖（习惯用语 / 直译会别扭的高频动作）
# ----------------------------------------------------------------------------
EXACT_OVERRIDE = {
    "3/4 sit-up": "四分之三仰卧起坐",
    "air bike": "空中自行车",
    "air squat": "徒手深蹲",
    "alternating plank": "交替平板支撑",
    "archer pull up": "射手引体向上",
    "archer push up": "射手俯卧撑",
    "arm slingers hanging bent knee legs": "悬垂摆臂屈膝",
    "arm slingers hanging straight legs": "悬垂摆臂直腿",
    "arms apart circular toe touch (male)": "分臂绕环触脚尖",
    "arms overhead full sit-up (male)": "过头全程仰卧起坐",
    "astride jumps (male)": "分腿跳",
    "back and forth step": "前后踏步",
    "back lever": "背水平",
    "back pec stretch": "背胸拉伸",
    "balance board": "平衡板",
    "band alternating v-up": "弹力带交替V字起身",
    "band assisted wheel rollerout": "弹力带辅助滚轮",
    "band close-grip pulldown": "弹力带窄握下拉",
    "band close-grip push-up": "弹力带窄握俯卧撑",
    "band fixed back close grip pulldown": "弹力带固定背窄握下拉",
    "band fixed back underhand pulldown": "弹力带固定背反握下拉",
    "band horizontal pallof press": "弹力带水平帕洛夫推",
    "band jack knife sit-up": "弹力带折刀仰卧起坐",
    "band kneeling one arm pulldown": "弹力带跪姿单臂下拉",
    "bird dog": "鸟狗式",
    "bear crawl": "熊爬",
    "bicycle crunch": "自行车卷腹",
    "box jump": "跳箱",
    "bulgarian split squat": "保加利亚分腿蹲",
    "burpee": "波比跳",
    "cable crossover": "绳索交叉夹胸",
    "chest dip": "胸肌臂屈伸",
    "chin up": "反握引体向上",
    "clean and jerk": "挺举",
    "conventional deadlift": "传统硬拉",
    "cross body crunch": "交叉卷腹",
    "dead bug": "死虫",
    "decline sit up": "下斜仰卧起坐",
    "double crunch": "双重卷腹",
    "dumbbell pullover": "哑铃颈后臂屈伸",
    "face pull": "面拉",
    "farmers walk": "农夫行走",
    "flat bench press": "平板卧推",
    "flutter kick": "交替踢腿",
    "foam roll": "泡沫轴滚动",
    "frog pump": "蛙式臀推",
    "front lever": "前水平",
    "german hang": "德式悬垂",
    "glute bridge": "臀桥",
    "good morning": "早安式体前屈",
    "gorilla row": "猩猩划船",
    "handstand push up": "倒立俯卧撑",
    "hanging leg raise": "悬垂举腿",
    "hip thrust": "臀推",
    "incline bench press": "上斜卧推",
    "incline curl": "上斜弯举",
    "jackknife sit up": "折刀仰卧起坐",
    "jumping jack": "开合跳",
    "jump rope": "跳绳",
    "kettlebell snatch": "壶铃抓举",
    "kipping pull up": "借力引体",
    "knee raise": "举膝",
    "lateral lunge": "侧箭步蹲",
    "lat pulldown": "高位下拉",
    "leg curl": "腿弯举",
    "leg extension": "腿伸展",
    "leg press": "腿举",
    "lying leg curl": "俯卧腿弯举",
    "mountain climber": "登山者",
    "muscle up": "双力臂",
    "neutral grip pull up": "对握引体向上",
    "pallof press": "帕洛夫抗旋转推",
    "plank": "平板支撑",
    "planche": "俄式挺身",
    "pull up": "引体向上",
    "push up": "俯卧撑",
    "rack pull": "架上硬拉",
    "rear delt fly": "后束反向飞鸟",
    "reverse crunch": "反向卷腹",
    "reverse fly": "反向飞鸟",
    "romanian deadlift": "罗马尼亚硬拉",
    "russian twist": "俄罗斯转体",
    "scapular pull up": "肩胛引体",
    "scissor kick": "剪刀踢",
    "seated calf raise": "坐姿提踵",
    "shrug": "耸肩",
    "side bend": "体侧屈",
    "side crunch": "侧卷腹",
    "side plank": "侧平板",
    "sit up": "仰卧起坐",
    "skull crusher": "仰卧臂屈伸",
    "snatch": "抓举",
    "split squat": "分腿蹲",
    "squat": "深蹲",
    "standing calf raise": "站姿提踵",
    "step up": "登阶",
    "stiff leg deadlift": "直腿硬拉",
    "sumo deadlift": "相扑硬拉",
    "superman": "超人式",
    "t bar row": "T杠划船",
    "thruster": "推举深蹲",
    "toe touch": "触脚尖",
    "torso rotation": "躯干旋转",
    "tuck jump": "收腹跳",
    "twisting sit up": "转体仰卧起坐",
    "upright row": "直立划船",
    "v up": "V字起身",
    "wall sit": "靠墙静蹲",
    "weighted sit up": "负重仰卧起坐",
    "wide grip pull up": "宽握引体向上",
    "windmill": "风车",
    "wood chop": "伐木",
    "wrist curl": "腕弯举",
    "zercher squat": "泽奇深蹲",
    "zottman curl": "佐特曼弯举",
    "all fours squad stretch": "四点支撑拉伸",
    "alternate heel touchers": "交替触踵",
    "ankle circles": "踝绕环",
    "assisted chest dip (kneeling)": "辅助胸肌臂屈伸(跪姿)",
    "assisted hanging knee raise": "辅助悬垂举膝",
    "assisted hanging knee raise with throw down": "辅助悬垂举膝下抛",
    "assisted lying gluteus and piriformis stretch": "辅助仰卧臀肌梨状肌拉伸",
    "assisted lying leg raise with lateral throw down": "辅助仰卧举腿侧下抛",
    "assisted lying leg raise with throw down": "辅助仰卧举腿下抛",
    "assisted motion russian twist": "辅助俄罗斯转体",
    "assisted parallel close grip pull-up": "辅助平行窄握引体向上",
    "assisted prone rectus femoris stretch": "辅助俯卧股直肌拉伸",
    "assisted seated pectoralis major stretch with stability ball": "辅助坐姿健身球胸大肌拉伸",
    "assisted side lying adductor stretch": "辅助侧卧内收肌拉伸",
    "assisted standing triceps extension (with towel)": "辅助站姿三头伸展(毛巾)",
    "assisted triceps dip (kneeling)": "辅助三头臂屈伸(跪姿)",
    "assisted wide-grip chest dip (kneeling)": "辅助宽握胸肌臂屈伸(跪姿)",
    "back extension on exercise ball": "健身球背伸展",
}

# 预排序（长度降序）用于贪心匹配
EQUIPMENT_SORTED = sorted(EQUIPMENT.keys(), key=len, reverse=True)
MOVEMENT_SORTED = sorted(MOVEMENT.keys(), key=len, reverse=True)


def translate_name(name: str) -> str:
    """把英文动作名翻成中文。未命中返回原英文（保证不丢字段）。"""
    if not name:
        return name
    key = name.strip().lower()
    if key in EXACT_OVERRIDE:
        return EXACT_OVERRIDE[key]

    # 剥离标点，避免 (kneeling) / 's 之类粘连
    s = re.sub(r"[^\w\s]", " ", key)
    s = s.replace("-", " ").replace("/", " ").replace("  ", " ")

    # 1) 装备前缀（可能多个，循环匹配）
    equip_parts = []
    while True:
        hit = False
        for ph in EQUIPMENT_SORTED:
            if ph in s:
                equip_parts.append(EQUIPMENT[ph])
                s = s.replace(ph, " ", 1)
                hit = True
                break
        if not hit:
            break
    equip = "".join(equip_parts)

    # 2) 动作主体（一个名字可能含多个动作，循环匹配）
    movement_parts = []
    while True:
        hit = False
        for ph in MOVEMENT_SORTED:
            if ph in s:
                movement_parts.append(MOVEMENT[ph])
                s = s.replace(ph, " ", 1)
                hit = True
                break
        if not hit:
            break
    movement = "".join(movement_parts)

    # 3) 修饰词 + 其余词
    prefix_mods, suffix_mods, pre_words, post_words = [], [], [], []
    for tok in s.split():
        if not tok:
            continue
        if tok in MODIFIER_PREFIX:
            prefix_mods.append(MODIFIER_PREFIX[tok])
        elif tok in MODIFIER_SUFFIX:
            suffix_mods.append(MODIFIER_SUFFIX[tok])
        elif tok in MUSCLE_WORD:
            pre_words.append(MUSCLE_WORD[tok])
        elif tok in WORD_MAP:
            mapped = WORD_MAP[tok]
            if mapped:
                post_words.append(mapped)
        else:
            cand = tok
            if cand.endswith("s") and len(cand) > 3:
                c2 = cand[:-1]
                if c2 in MODIFIER_PREFIX:
                    prefix_mods.append(MODIFIER_PREFIX[c2]); continue
                if c2 in MUSCLE_WORD:
                    pre_words.append(MUSCLE_WORD[c2]); continue
                if c2 in WORD_MAP and WORD_MAP[c2]:
                    post_words.append(WORD_MAP[c2]); continue
                c3 = cand[:-2] if cand.endswith("es") else None
                if c3 and c3 in MOVEMENT:
                    movement_parts.append(MOVEMENT[c3]); continue
                if c3 and c3 in WORD_MAP and WORD_MAP[c3]:
                    post_words.append(WORD_MAP[c3]); continue
            post_words.append(tok)  # 未知词保留英文

    parts = prefix_mods + pre_words
    if equip:
        parts.append(equip)
    if movement:
        parts.append(movement)
    parts += suffix_mods + post_words

    result = "".join(p for p in parts if p).strip()
    return result if result else name


# ----------------------------------------------------------------------------
# 分类标签翻译
# ----------------------------------------------------------------------------
BODYPART_ZH = {
    "back": "背部",
    "cardio": "有氧",
    "chest": "胸部",
    "lower arms": "前臂",
    "lower legs": "小腿",
    "neck": "颈部",
    "shoulders": "肩部",
    "upper arms": "上臂",
    "upper legs": "大腿",
    "waist": "腰腹",
}

MUSCLE_ZH = {
    "pectorals": "胸大肌",
    "chest": "胸部",
    "biceps": "肱二头肌",
    "triceps": "肱三头肌",
    "abs": "腹肌",
    "abdominals": "腹肌",
    "rectus abdominis": "腹直肌",
    "obliques": "腹斜肌",
    "external obliques": "腹外斜肌",
    "glutes": "臀肌",
    "gluteus maximus": "臀大肌",
    "gluteus medius": "臀中肌",
    "glute": "臀部",
    "hamstrings": "腘绳肌",
    "hamstring": "腘绳肌",
    "quadriceps": "股四头肌",
    "quads": "股四头肌",
    "quad": "股四头",
    "calves": "小腿",
    "calf": "小腿",
    "gastrocnemius": "腓肠肌",
    "soleus": "比目鱼肌",
    "shoulders": "肩部",
    "delts": "三角肌",
    "deltoids": "三角肌",
    "deltoid": "三角肌",
    "anterior deltoid": "前束三角肌",
    "front delts": "前束",
    "lateral deltoid": "中束三角肌",
    "side delts": "中束",
    "rear deltoid": "后束三角肌",
    "traps": "斜方肌",
    "trapezius": "斜方肌",
    "trap": "斜方肌",
    "lats": "背阔肌",
    "latissimus dorsi": "背阔肌",
    "lat": "背阔肌",
    "lower back": "下背",
    "erector spinae": "竖脊肌",
    "spinal erectors": "竖脊肌",
    "hip flexors": "髋屈肌",
    "adductors": "内收肌",
    "abductors": "外展肌",
    "forearms": "前臂",
    "forearm": "前臂",
    "neck": "颈部",
    "serratus anterior": "前锯肌",
    "rotator cuff": "肩袖",
    "groin": "腹股沟",
    "upper chest": "上胸",
    "lower chest": "下胸",
    "middle back": "中背",
    "full back": "全背",
}


def translate_body_part(value: str) -> str:
    return BODYPART_ZH.get((value or "").strip().lower(), value or "")


def translate_equipment(value: str) -> str:
    if not value:
        return value or ""
    v = value.strip().lower()
    for ph in EQUIPMENT_SORTED:
        if ph == v or ph in v:
            return EQUIPMENT[ph]
    words = [EQUIPMENT.get(w, w) for w in re.sub(r"[^\w\s]", " ", v).replace("-", " ").split()]
    return "".join(words) if words else value


def translate_muscle(value: str) -> str:
    if not value:
        return value or ""
    return MUSCLE_ZH.get(value.strip().lower(), value)


def translate_muscle_list(values: list) -> list:
    if not values:
        return []
    return [translate_muscle(v) for v in values]
